/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2016-12-11 08:53:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.ch09;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class member_005fupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=javascript>\r\n");
      out.write("function valid_check()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("if (document.frm1.usernm.value == \"\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"이름을 입력하여 주시기 바랍니다.\");\r\n");
      out.write("document.frm1.usernm.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("if (document.frm1.passwd.value == \"\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"비밀번호를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("document.frm1.passwd.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("if (document.frm1.passwd.value != document.frm1.passwd2.value)\r\n");
      out.write("{\r\n");
      out.write("alert(\"비밀번호가 다릅니다.  확인하여 주시기 바랍니다.\");\r\n");
      out.write("document.frm1.passwd.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if (document.frm1.phone1.value.length < 3)\r\n");
      out.write("{\r\n");
      out.write("  alert(\"전화번호를 다시 확인해주세요\");\r\n");
      out.write("  document.frm1.phone1.focus();\r\n");
      out.write("  return false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if (document.frm1.phone2.value.length < 4)\r\n");
      out.write("{\r\n");
      out.write("  alert(\"전화번호를 다시 확인해주세요\");\r\n");
      out.write("  document.frm1.phone2.focus();\r\n");
      out.write("  return false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if (document.frm1.phone3.value.length < 4)\r\n");
      out.write("{\r\n");
      out.write("  alert(\"전화번호를 다시 확인해주세요\");\r\n");
      out.write("  document.frm1.phone3.focus();\r\n");
      out.write("  return false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("for (var i = 0; i < document.frm1.phone1.value.length; i++)\r\n");
      out.write("{\r\n");
      out.write("if (document.frm1.phone1.value.charAt(i) < \"0\" || document.frm1.phone1.value.charAt(i) > \"9\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"전화번호는 숫자만 가능합니다.\");\r\n");
      out.write("document.frm1.jumin1.focus();\r\n");
      out.write("return;  }   }\r\n");
      out.write("\r\n");
      out.write("for (var i = 0; i < document.frm1.phone2.value.length; i++)\r\n");
      out.write("{\r\n");
      out.write("if (document.frm1.phone2.value.charAt(i) < \"0\" || document.frm1.phone2.value.charAt(i) > \"9\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"전화번호는 숫자만 가능합니다.\");\r\n");
      out.write("document.frm1.jumin2.focus();\r\n");
      out.write("return;  }  }  \r\n");
      out.write("\r\n");
      out.write("for (var i = 0; i < document.frm1.phone3.value.length; i++)\r\n");
      out.write("{\r\n");
      out.write("if (document.frm1.phone3.value.charAt(i) < \"0\" || document.frm1.phone3.value.charAt(i) > \"9\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"전화번호는 숫자만 가능합니다.\");\r\n");
      out.write("document.frm1.jumin2.focus();\r\n");
      out.write("return;  }  } \r\n");
      out.write("\r\n");
      out.write("if (document.frm1.addr1.value == \"\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"주소를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("document.frm1.addr1.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if (document.frm1.addr2.value == \"\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"주소를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("document.frm1.addr2.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("document.frm1.submit();\r\n");
      out.write("}\r\n");
      out.write("function KeyNumber()\r\n");
      out.write("{\r\n");
      out.write("var event_key = event.keyCode;\r\n");
      out.write("\r\n");
      out.write("if((event_key < 48 || event_key > 57) && (event_key != 8 && event_key != 46))\r\n");
      out.write("{\r\n");
      out.write("event.returnValue=false;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("function cursor_move(a)\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("if ( a == 1 )\r\n");
      out.write("{\r\n");
      out.write("var str = document.frm1.phone1.value.length;\r\n");
      out.write("if (str == 3) \r\n");
      out.write("document.frm1.phone2.focus();\r\n");
      out.write("}\r\n");
      out.write("else if ( a == 2 )\r\n");
      out.write("{\r\n");
      out.write("var str = document.frm1.phone2.value.length;\r\n");
      out.write("if (str == 4) \r\n");
      out.write("document.frm1.phone3.focus();\r\n");
      out.write("}\r\n");
      out.write("else if ( a == 3 )\r\n");
      out.write("{\r\n");
      out.write("var str = document.frm1.phone3.value.length;\r\n");
      out.write("if (str == 4) \r\n");
      out.write("document.frm1.addr1.focus();\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

String in_userid = request.getParameter("puserid");
//String usernm = request.getParameter("pusernm");
//String in_jumin1 = request.getParameter("pjumin1");
//String in_jumin2 = request.getParameter("pjumin2");

Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
String connectionURL = "jdbc:sqlserver://localhost:1433;databaseName=DBPstudio;user=sa;password=11";
Connection con = DriverManager.getConnection(connectionURL);
PreparedStatement pstmt = null;
ResultSet rs = null;

String SQL = "select * from Member where M_ID = ?";
pstmt = con.prepareStatement(SQL);
pstmt.setString(1, in_userid);
rs = pstmt.executeQuery();

if (rs.next()==false)
	   out.print("등록되지 않은 회원입니다.");
	else
	{
		String usernm= rs.getString("M_NAME");
		String phone= rs.getString("M_PHONE");

				String phone1= "";
				String phone2= "";
				String phone3= "";
			          if (phone != null)  {
			        	  phone1= phone.substring(0, 3);
			        	  phone2= phone.substring(3,7);
			        	  phone3= phone.substring(7,11);
						}
		
		String pass= rs.getString("M_PASSWORD");
		String addr1= rs.getString("M_ADDRESS1");
		String addr2= rs.getString("M_ADDRESS2");

      out.write("\r\n");
      out.write("\r\n");
      out.write(" <h2>My Info</h2><BODY>\r\n");
      out.write("<!--form action=\"member_join_ok.jsp\" method=\"post\"-->\r\n");
      out.write("<form Name=\"frm1\" action=\"/LSJ_PHOTO/ch09/member_update_ok.jsp\" method=\"post\">\r\n");
      out.write("<center>\r\n");
      out.write("<!--아이디 히든시키기 -->\r\n");
      out.write("<!-- <INPUT TYPE = \"hidden\" NAME = \"userid\" VALUE=\"");
      out.print(in_userid);
      out.write("\"> -->\r\n");
      out.write("<TABLE WIDTH = \"500\" BORDER = \"0\" CellPadding = \"5\" CellSpacing = \"0\">\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\" ><font size = 2>아이디</font></TD>\r\n");
      out.write("<TD width = \"80%\" ALIGN = \"left\" >\r\n");
      out.write("<!--%=in_userid%  -->\r\n");
      out.write("<INPUT TYPE = \"text\" SIZE = \"15\" MAXLENGTH = \"10\" NAME = \"userid1\" VALUE=\"");
      out.print( in_userid );
      out.write("\" disabled>\r\n");
      out.write("<INPUT TYPE = \"hidden\" NAME = \"userid\" VALUE=\"");
      out.print(in_userid);
      out.write("\">\r\n");
      out.write("</TD></TR>\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\"><font size = 2>이름</font></TD>\r\n");
      out.write("<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("<INPUT TYPE = \"text\" SIZE = \"15\" MAXLENGTH = \"10\" NAME = \"usernm\" VALUE=\"");
      out.print( usernm );
      out.write("\">\r\n");
      out.write("</TD></TR>\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\"><font size = 2>비밀번호</font></TD>\r\n");
      out.write("<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("<INPUT TYPE = \"password\" SIZE = \"10\" MAXLENGTH = \"10\" NAME = \"passwd\">\r\n");
      out.write("</TD></TR>\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\"><font size = 2>비밀번호 확인</font></TD>\r\n");
      out.write("<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("<INPUT TYPE = \"password\" SIZE = \"10\" MAXLENGTH = \"10\" NAME = \"passwd2\">\r\n");
      out.write("</TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\"><font size = 2>연락처</font></TD>\r\n");
      out.write("<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("<INPUT TYPE = \"text\" SIZE = \"3\" MAXLENGTH = \"3\" NAME = \"phone1\" VALUE=\"");
      out.print( phone1 );
      out.write("\">-\r\n");
      out.write("<INPUT TYPE = \"text\" SIZE = \"4\" MAXLENGTH = \"4\" NAME = \"phone2\" VALUE=\"");
      out.print( phone2 );
      out.write("\">-\r\n");
      out.write("<INPUT TYPE = \"text\" SIZE = \"4\" MAXLENGTH = \"4\" NAME = \"phone3\" VALUE=\"");
      out.print( phone3 );
      out.write("\">\r\n");
      out.write("</TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\"><font size = 2>주소</font></TD>\r\n");
      out.write("<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("<INPUT TYPE = \"text\" SIZE = \"30\" MAXLENGTH = \"30\" NAME = \"addr1\" VALUE=\"");
      out.print( addr1 );
      out.write("\">\r\n");
      out.write("</TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\"><font size = 2>상세주소</font></TD>\r\n");
      out.write("<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("<INPUT TYPE = \"text\" SIZE = \"30\" MAXLENGTH = \"30\" NAME = \"addr2\" VALUE=\"");
      out.print( addr2 );
      out.write("\">\r\n");
      out.write("</TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("<TD WIDTH = \"100%\" ALIGN = \"center\" COLSPAN = \"2\">\r\n");
      out.write("<INPUT TYPE = \"button\" VALUE = \"수정하기\" onclick=\"valid_check()\">\r\n");
      out.write("</TD></TR>\r\n");
      out.write("\r\n");
      out.write("</TABLE>\r\n");
      out.write("</center>\r\n");
      out.write("</FORM>\r\n");
      out.write("</BODY>\r\n");

	}

      out.write("\r\n");
      out.write("</HTML>\r\n");
      out.write("       \r\n");
      out.write("       ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
