/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2016-11-30 10:22:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class member_005fjoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=javascript>\r\n");
      out.write("function valid_check()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("if (document.frm1.userid.value == \"\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"아이디를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("document.frm1.userid.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if (document.frm1.userid.value.length < 6)\r\n");
      out.write("{\r\n");
      out.write("alert(\"아이디는 6자 이상입니다.\");\r\n");
      out.write("document.frm1.userid.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("if (document.frm1.usernm.value == \"\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"이름을 입력하여 주시기 바랍니다.\");\r\n");
      out.write("document.frm1.usernm.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("if (document.frm1.passwd.value == \"\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"비밀번호를 입력하여 주시기 바랍니다.\");\r\n");
      out.write("document.frm1.passwd.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("if (document.frm1.passwd.value != document.frm1.passwd2.value)\r\n");
      out.write("{\r\n");
      out.write("alert(\"비밀번호가 다릅니다.  확인하여 주시기 바랍니다.\");\r\n");
      out.write("document.frm1.passwd.focus();\r\n");
      out.write("return false;\r\n");
      out.write("}\r\n");
      out.write("if (document.frm1.jumin1.value.length != 6)\r\n");
      out.write("{\r\n");
      out.write("  alert(\"주민번호 앞 자릿수는 6자입니다.\");\r\n");
      out.write("  document.frm1.jumin1.focus();\r\n");
      out.write("  return false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("if (document.frm1.jumin2.value.length != 7)\r\n");
      out.write("{\r\n");
      out.write("  alert(\"주민번호 뒷 자릿수는 7자입니다.\");\r\n");
      out.write("  document.frm1.jumin2.focus();\r\n");
      out.write("  return false;\r\n");
      out.write("}\r\n");
      out.write("for (var i = 0; i < document.frm1.jumin1.value.length; i++)\r\n");
      out.write("{\r\n");
      out.write("if (document.frm1.jumin1.value.charAt(i) < \"0\" || document.frm1.jumin1.value.charAt(i) > \"9\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"주민등록번호는 숫자만 가능합니다.\");\r\n");
      out.write("document.frm1.jumin1.focus();\r\n");
      out.write("return;  }   }\r\n");
      out.write("\r\n");
      out.write("for (var i = 0; i < document.frm1.jumin2.value.length; i++)\r\n");
      out.write("{\r\n");
      out.write("if (document.frm1.jumin2.value.charAt(i) < \"0\" || document.frm1.jumin2.value.charAt(i) > \"9\")\r\n");
      out.write("{\r\n");
      out.write("alert(\"주민등록번호는 숫자만 가능합니다.\");\r\n");
      out.write("document.frm1.jumin2.focus();\r\n");
      out.write("return;  }  }  \r\n");
      out.write("\r\n");
      out.write("document.frm1.submit();\r\n");
      out.write("}\r\n");
      out.write("function KeyNumber()\r\n");
      out.write("{\r\n");
      out.write("var event_key = event.keyCode;\r\n");
      out.write("\r\n");
      out.write("if((event_key < 48 || event_key > 57) && (event_key != 8 && event_key != 46))\r\n");
      out.write("{\r\n");
      out.write("event.returnValue=false;\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write("function cursor_move(a)\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("if ( a == 1 )\r\n");
      out.write("{\r\n");
      out.write("var str = document.frm1.jumin1.value.length;\r\n");
      out.write("if (str == 6) \r\n");
      out.write("document.frm1.jumin2.focus();\r\n");
      out.write("}\r\n");
      out.write("else if ( a == 2 )\r\n");
      out.write("{\r\n");
      out.write("var str = document.frm1.jumin2.value.length;\r\n");
      out.write("if (str == 7) \r\n");
      out.write("document.frm1.mailrcv.focus();\r\n");
      out.write("}\r\n");
      out.write("}\r\n");
      out.write(" </script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <h3>회원 가입</h3><BODY>\r\n");
      out.write("<!--form action=\"member_join_ok.jsp\" method=\"post\"-->\r\n");
      out.write("<form Name=\"frm1\" action=\"member_join_ok.jsp\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<TABLE WIDTH = \"500\" BORDER = \"1\" CellPadding = \"0\" CellSpacing = \"0\">\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\" >아이디</TD>\r\n");
      out.write("<TD width = \"80%\" ALIGN = \"left\" >\r\n");
      out.write("<INPUT TYPE = \"text\" SIZE = \"15\" MAXLENGTH = \"10\" NAME = \"userid\">\r\n");
      out.write("</TD></TR>\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\">이름</TD>\r\n");
      out.write("<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("<INPUT TYPE = \"text\" SIZE = \"15\" MAXLENGTH = \"10\" NAME = \"usernm\">\r\n");
      out.write("</TD></TR>\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\">비밀번호</TD>\r\n");
      out.write("<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("<INPUT TYPE = \"password\" SIZE = \"10\" MAXLENGTH = \"10\" NAME = \"passwd\">\r\n");
      out.write("</TD></TR>\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\">비밀번호확인</TD>\r\n");
      out.write("<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("<INPUT TYPE = \"password\" SIZE = \"10\" MAXLENGTH = \"10\" NAME = \"passwd2\">\r\n");
      out.write("</TD></TR>\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\">주민번호</TD>\r\n");
      out.write("        <TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("        <INPUT TYPE =\"text\" NAME=\"jumin1\" SIZE = \"6\" MAXLENGTH = \"6\"     \r\n");
      out.write("                 onKeyDown=\"KeyNumber()\" onKeyup=\"cursor_move(1) \">-\r\n");
      out.write("\r\n");
      out.write("<INPUT TYPE =\"text\" NAME=\"jumin2\" SIZE = \"7\" MAXLENGTH = \"7\"  \r\n");
      out.write("                 onKeyDown=\"KeyNumber()\" onKeyup=\"cursor_move(2) \">\r\n");
      out.write("\r\n");
      out.write("        </TD></TR>\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\">메일수신여부</TD>\r\n");
      out.write("        <TD WIDTH = \"60%\" ALIGN = \"left\"> 동의함 <INPUT TYPE =\"checkbox\" NAME=\"mailrcv\">\r\n");
      out.write("        </TD></TR>\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\">성별.</TD>\r\n");
      out.write("        <TD WIDTH = \"60%\" ALIGN = \"left\">남<INPUT TYPE =\"radio\" NAME=\"gender\" VALUE=\"1\">\r\n");
      out.write("                                                         여<INPUT TYPE =\"radio\" NAME=\"gender\" VALUE=\"2\">\r\n");
      out.write("        </TD></TR>\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\">직업</TD>\r\n");
      out.write("        <TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("        <SELECT NAME=\"job\">\r\n");
      out.write("         <OPTION VALUE=\"\">==직업을 선택하세요==</OPTION>\r\n");
      out.write("         <OPTION VALUE=\"1\">학생</OPTION>\r\n");
      out.write("         <OPTION VALUE=\"2\">회사원</OPTION>\r\n");
      out.write("        <OPTION VALUE=\"3\">군인</OPTION>\r\n");
      out.write("        <OPTION VALUE=\"9\">기타</OPTION>\r\n");
      out.write("        </SELECT>\r\n");
      out.write("       </TD></TR>\r\n");
      out.write("<TR><TD WIDTH = \"40%\" ALIGN = \"left\">자기소개</TD>\r\n");
      out.write("<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("<TEXTAREA NAME=\"intro\" ROWS=5 COLS=50></TEXTAREA>\r\n");
      out.write("</TD></TR>\r\n");
      out.write("\r\n");
      out.write("<TR>\r\n");
      out.write("<TD WIDTH = \"100%\" ALIGN = \"center\" COLSPAN = \"2\">\r\n");
      out.write("<INPUT TYPE = \"button\" VALUE = \"가입\" onclick=\"valid_check()\">\r\n");
      out.write("</TD></TR>\r\n");
      out.write("\r\n");
      out.write("</TABLE></FORM>\r\n");
      out.write("</BODY></HTML>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
