/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2016-12-10 07:52:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class addProduct_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n");
      out.write("<HTML>\r\n");
      out.write(" <HEAD>\r\n");
      out.write("  <TITLE>제품 업로드</TITLE>\r\n");
      out.write(" </HEAD>\r\n");
      out.write("\r\n");
      out.write("<script language=javascript>\r\n");
      out.write("function valid_check()\r\n");
      out.write("{\r\n");
      out.write("\tif (document.frm_file.category.value == \"\") \r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"카테고리를 선택하세요\");\r\n");
      out.write("\t\tdocument.frm_file.category.focus(); \r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif (document.frm_file.sub_category.value == \"\") \r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"세부 카테고리를 선택하세요\");\r\n");
      out.write("\t\tdocument.frm_file.sub_category.focus(); \r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif (document.frm_file.code.value == \"\") \r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"제품코드를 입력바랍니다\");\r\n");
      out.write("\t\tdocument.frm_file.code.focus(); \r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfor (var i = 0; i < document.frm_file.amount.value.length; i++)\r\n");
      out.write("\t{\r\n");
      out.write("\tif (document.frm_file.amount.value.charAt(i) < \"0\" || document.frm_file.amount.value.charAt(i) > \"9\")\r\n");
      out.write("\t{\r\n");
      out.write("\talert(\"개수는 숫자로 입력해주세요\");\r\n");
      out.write("\tdocument.frm1.jumin1.focus();\r\n");
      out.write("\treturn;  }   }\r\n");
      out.write("\t\r\n");
      out.write("\tif (document.frm_file.name.value == \"\") \r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"제품명을 입력바랍니다\");\r\n");
      out.write("\t\tdocument.frm_file.name.focus(); \r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tif (document.frm_file.price.value == \"\") \r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"가격을 입력바랍니다\");\r\n");
      out.write("\t\tdocument.frm_file.price.focus(); \r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfor (var i = 0; i < document.frm_file.price.value.length; i++)\r\n");
      out.write("\t{\r\n");
      out.write("\tif (document.frm_file.price.value.charAt(i) < \"0\" || document.frm_file.price.value.charAt(i) > \"9\")\r\n");
      out.write("\t{\r\n");
      out.write("\talert(\"가격은 숫자로 입력해주세요\");\r\n");
      out.write("\tdocument.frm1.jumin1.focus();\r\n");
      out.write("\treturn;  }   }\r\n");
      out.write("\t\r\n");
      out.write("\tif (document.frm_file.image.value == \"\") \r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"제품이미지를 첨부바랍니다\");\r\n");
      out.write("\t\tdocument.frm_file.image.focus(); \r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdocument.frm_file.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function doChange(srcE, targetId){\r\n");
      out.write("    var val = srcE.value;\r\n");
      out.write("    var targetE = document.getElementById(targetId);\r\n");
      out.write("    var url;\r\n");
      out.write("    targetE.length = 0;\r\n");
      out.write("    switch (val) {\r\n");
      out.write("      case \"1\" :\r\n");
      out.write("        addOption(['프레임', '1'], targetE);\r\n");
      out.write("        addOption(['용지', '2'], targetE);\r\n");
      out.write("      break;\r\n");
      out.write("\r\n");
      out.write("      case \"2\" :\r\n");
      out.write("        addOption(['커버', '3'], targetE);\r\n");
      out.write("        addOption(['용지', '4'], targetE);\r\n");
      out.write("      break;\r\n");
      out.write("      \r\n");
      out.write("      case \"3\" :\r\n");
      out.write("          addOption(['쿠션', '5'], targetE);\r\n");
      out.write("          addOption(['머그컵', '6'], targetE);\r\n");
      out.write("          addOption(['액세서리', '7'], targetE);\r\n");
      out.write("        break;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function addOption(text, obj) {\r\n");
      out.write("  obj.options[obj.length] = new Option(text[0] ,text[1]);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function submit_list()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.frm_file.action = \"/LSJ_PHOTO/home.jsp?page=/admin/productList\";\r\n");
      out.write("\tdocument.frm_file.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(" </script>\r\n");
      out.write("<h3>파일 업로드</h3>\r\n");
      out.write("<BODY>\r\n");
      out.write("<FORM NAME = \"frm_file\" ACTION = \"admin/addProduct_ok.jsp\" METHOD = \"post\" ENCTYPE=\"multipart/form-data\">\r\n");
      out.write("<TABLE WIDTH = \"600\" BORDER = \"0\" CellPadding = \"0\" CellSpacing = \"0\">\r\n");
      out.write("\t<TR><TD WIDTH = \"40%\" ALIGN = \"left\">카테고리</TD>\r\n");
      out.write("        <TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("        <SELECT NAME=\"category\" id=\"category\" onchange=\"doChange(this, 'sub_category')\">\r\n");
      out.write("        <OPTION VALUE=\"\">==카테고리==</OPTION>\r\n");
      out.write("        <OPTION VALUE=\"1\">액자</OPTION>\r\n");
      out.write("        <OPTION VALUE=\"2\">앨범</OPTION>\r\n");
      out.write("        <OPTION VALUE=\"3\">디자인 소품</OPTION>\r\n");
      out.write("        </SELECT>\r\n");
      out.write("        \r\n");
      out.write("        <SELECT NAME=\"sub_category\" id=\"sub_category\">\r\n");
      out.write("       \t<OPTION VALUE=\"\">==세부 카테고리==</OPTION>\r\n");
      out.write("      \t</SELECT>\r\n");
      out.write("\r\n");
      out.write("       </TD>\r\n");
      out.write("    </TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD WIDTH = \"40%\" ALIGN = \"left\">제품코드</TD>\r\n");
      out.write("\t\t<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("\t\t\t<INPUT TYPE = \"text\" SIZE = \"50\" MAXLENGTH = \"10\" NAME = \"code\">\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD WIDTH = \"40%\" ALIGN = \"left\">개수</TD>\r\n");
      out.write("\t\t<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("\t\t\t<INPUT TYPE = \"text\" SIZE = \"50\" MAXLENGTH = \"10\" NAME = \"amount\">\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD WIDTH = \"40%\" ALIGN = \"left\">제품명</TD>\r\n");
      out.write("\t\t<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("\t\t\t<INPUT TYPE =\"text\" NAME=\"name\" SIZE = \"50\" MAXLENGTH = \"50\">\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD WIDTH = \"40%\" ALIGN = \"left\">가격</TD>\r\n");
      out.write("\t\t<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("\t\t\t<INPUT TYPE =\"text\" NAME=\"price\" SIZE = \"50\" MAXLENGTH = \"50\">\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD WIDTH = \"40%\" ALIGN = \"left\">제품설명</TD>\r\n");
      out.write("\t\t<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("\t\t\t<TEXTAREA NAME=\"text\" ROWS=5 COLS=50></TEXTAREA>\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD WIDTH = \"40%\" ALIGN = \"left\">제품 이미지</TD>\r\n");
      out.write("\t\t<TD WIDTH = \"60%\" ALIGN = \"left\">\r\n");
      out.write("\t\t\t<INPUT TYPE =\"file\" NAME=\"image\" >\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD WIDTH = \"100%\" ALIGN = \"center\" COLSPAN = \"2\">\r\n");
      out.write("\t\t<TABLE>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD WIDTH = \"33%\" ALIGN = \"center\">\r\n");
      out.write("\t\t\t\t\t<INPUT TYPE = \"reset\" VALUE = \"다시 작성\">\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t<TD WIDTH = \"34%\" ALIGN = \"center\">\r\n");
      out.write("\t\t\t\t\t<INPUT TYPE = \"button\" VALUE = \"등록\" onClick=\"valid_check()\">\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t<TD WIDTH = \"33%\" ALIGN = \"center\">\r\n");
      out.write("\t\t\t\t\t<INPUT TYPE = \"button\" VALUE = \"목록으로\" onClick = \"submit_list()\">\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t</TABLE>\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("</TABLE>\r\n");
      out.write("</FORM>\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
