CREATE TABLE Member(
M_ID CHAR(18) PRIMARY KEY NOT NULL,
M_NAME CHAR(18) NOT NULL,
M_PASSWORD CHAR(18) NOT NULL,
M_PHONE CHAR(18) NOT NULL,
M_ADDRESS1 CHAR(20) NOT NULL,
M_ADDRESS2 CHAR(30) NOT NULL
);

CREATE TABLE Category(
Category_Num INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Category_Name CHAR(18) NOT NULL
);

CREATE TABLE Sub_Category(
Sub_Category_Num INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Sub_Category_Name INT NOT NULL,
Category_Num INT FOREIGN KEY REFERENCES Category(Category_Num) NOT NULL
);

CREATE TABLE Product(
Product_Code CHAR(18) PRIMARY KEY NOT NULL,
Product_Name CHAR(18) NOT NULL,
Product_Image CHAR(30) NOT NULL,
Product_Amount INT NOT NULL,
product_Price MONEY NOT NULL,
Product_Info CHAR(200),
Product_Popular INT NOT NULL,
SubCategory_Num INT FOREIGN KEY REFERENCES Category(Category_Num) NOT NULL,
UserID CHAR(18) FOREIGN KEY REFERENCES Member (M_ID) NOT NULL
);

CREATE TABLE CustomDesign(
D_NUM INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
D_NAME CHAR(18) NOT NULL,
D_CA INT FOREIGN KEY REFERENCES Category(Category_Num) NOT NULL,
UserID CHAR(18) FOREIGN KEY REFERENCES Member(M_ID) NOT NULL
);

CREATE TABLE Design_Option(
D_Option_Num CHAR(18) PRIMARY KEY NOT NULL,
D_NUM INT FOREIGN KEY REFERENCES CustomDesign(D_NUM) NOT NULL,
Product_Code CHAR(18) FOREIGN KEY REFERENCES Product(Product_Code) NOT NULL
);

CREATE TABLE Orders(
O_Num CHAR(25) PRIMARY KEY NOT NULL,
O_DATE DATETIME DEFAULT GETDATE() NOT NULL,
O_TEXT CHAR(200),
O_UserID CHAR(18) FOREIGN KEY REFERENCES Product(Product_Code) NOT NULL
);

CREATE TABLE Orders_Info(
OINFO_Num CHAR(18) PRIMARY KEY NOT NULL,
OINFO_Price MONEY NOT NULL,
OINFO_File CHAR(30) NOT NULL,
OINFO_OrderNum CHAR(25) FOREIGN KEY REFERENCES Orders(O_Num) NOT NULL,
OINFO_DesignNum INT FOREIGN KEY REFERENCES CustomDesign(D_NUM) NOT NULL
);