/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.39
 * Generated at: 2016-12-10 09:18:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Order;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class orderWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("utf-8"); 
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n");
      out.write("<HTML>\r\n");
      out.write(" <HEAD>\r\n");
      out.write("  <TITLE>주문작성</TITLE>\r\n");
      out.write(" </HEAD>\r\n");
      out.write("\r\n");
      out.write("<script language=javascript>\r\n");
      out.write("function valid_check()\r\n");
      out.write("{\r\n");
      out.write("\r\n");
      out.write("\tif (document.frm1.name.value == \"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"주문자명을 입력바랍니다\");\r\n");
      out.write("\t\tdocument.frm1.writername.focus(); \r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tif (document.frm1.addr1.value == \"\") \r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"주소를 입력바랍니다\");\r\n");
      out.write("\t\tdocument.frm1.addr1.focus(); \r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif (document.frm1.addr2.value == \"\") \r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"상세 주소를 입력바랍니다\");\r\n");
      out.write("\t\tdocument.frm1.addr2.focus(); \r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tif (document.frm1.file.value == \"\") \r\n");
      out.write("\t{\r\n");
      out.write("\t\talert(\"제작을 맡기실 사진 파일을 업로드 해주세요\");\r\n");
      out.write("\t\tdocument.frm1.file.focus(); \r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tdocument.frm1.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function submit_list()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.frm1.action = \"/LSJ_PHOTO/home.jsp?page=/CustomDesign/customDesign\";\r\n");
      out.write("\tdocument.frm1.submit();\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");

int check= Integer.valueOf(request.getParameter("check"));
int dnum= Integer.valueOf(request.getParameter("d_num"));
int allPrice= Integer.valueOf(request.getParameter("all"));
String ID = (String)session.getAttribute("G_MEMID");
   if (ID == null)
   {
	   out.println("<script language=javascript>");
	   out.println("alert('로그인 후 이용해주세요');");
	   //out.println("location.href='home.jsp';");
	   out.println("location.href='/LSJ_PHOTO/home.jsp?page=/ch09/member_login';");
	   out.println("</script>");
   }
   
   if (check == 0)
   {
	   out.println("<script language=javascript>");
	   out.println("alert('모든 옵션을 추가한 뒤 주문해주세요');");
	   //out.println("location.href='home.jsp';");
	   out.println("location.href='/LSJ_PHOTO/home.jsp?page=/CustomDesign/customDesign';");
	   out.println("</script>");
   }
   
   
   
   
   
   Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
   String connectionURL = "jdbc:sqlserver://localhost:1433;databaseName=DBPstudio;user=sa;password=11";
   Connection con = DriverManager.getConnection(connectionURL);
   PreparedStatement pstmt = null;
   ResultSet rs = null;		// 데이터 베이스에서 가져온 정보를 저장하는 객체 
   ResultSet rs2 = null;      // paging    rs 객체 하나 더 생성 
   ResultSet rso = null;      // option


      //String SQL = "select userid, usernm, gender, jumin, jobcd from members order by userid";
        
      
	String SQL = "SELECT * from Member where M_ID = ?";
        
	pstmt = con.prepareStatement(SQL);
	pstmt.setString(1, ID);
	rs = pstmt.executeQuery();
    	
	if(rs.next())    
	{
   		String name= rs.getString("M_NAME");
   		String phone= rs.getString("M_PHONE");
   		String addr1= rs.getString("M_ADDRESS1");
		String addr2= rs.getString("M_ADDRESS2");
		
		String phone1= "";
		String phone2= "";
		String phone3= "";
	          if (phone != null)  {
	        	  phone1= phone.substring(0, 3);
	        	  phone2= phone.substring(3,7);
	        	  phone3= phone.substring(7,11);
				}
	    phone=phone1+"-"+phone2+"-"+phone3;
	
      
      
	String SQL2 = "SELECT * from CustomDesign where UserID = ? and D_Num = ?";
      
	pstmt = con.prepareStatement(SQL2);
	pstmt.setString(1, ID);
	pstmt.setInt(2, dnum);
	rs2 = pstmt.executeQuery();
	
	if(rs2.next())    
	   {
		    int d_num= rs2.getInt("D_NUM");
			String d_name= rs2.getString("D_NAME");
	       
			
			String SQL_O="SELECT P.Product_Name, P.SubCategory_Num, P.Product_Price, P.Product_Image ";
			SQL_O = SQL_O +"FROM Design_Option D, Product P where D.D_NUM = ? and D.Product_Code=P.Product_Code ";
			pstmt = con.prepareStatement(SQL_O);
			pstmt.setInt(1, dnum);
	  		rso = pstmt.executeQuery();


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<BODY>\r\n");
      out.write("<FORM NAME = \"frm1\" ACTION = \"/LSJ_PHOTO/Order/orderWrite_ok.jsp\" METHOD = \"post\" ENCTYPE=\"multipart/form-data\">\r\n");
      out.write("\r\n");
      out.write("<img src=\"homepageImage/MyPage/orderTitle.png\" height=\"60\" border=\"0\"/>\r\n");
      out.write("\r\n");
      out.write("\t<Table WIDTH = \"550\">\r\n");
      out.write("\t<TR bgcolor = \"EAEAEA\">\r\n");
      out.write("\t<TD WIDTH = \"100%\" ALIGN = \"left\" COLSPAN = \"4\"><font size = 2>디자인 이름 : ");
      out.print(d_name );
      out.write("</font></TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t");

		while(rso.next())
	  	{
	  		int sub_category= rso.getInt("SubCategory_Num");
	 		String p_name= rso.getString("Product_Name");
	  		String p_image= rso.getString("Product_Image");
			int p_price= rso.getInt("Product_Price");
	
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t   \t \t<TR bgcolor = \"F6F6F6\">\r\n");
      out.write("\t   \t \t<INPUT TYPE = \"hidden\" NAME = \"dnum\" VALUE=\"");
      out.print(dnum);
      out.write("\">\r\n");
      out.write("\t   \t\t<TD width=\"15%\"><font size = 2><center>");
      out.print(sub_category);
      out.write("</center></font></TD>   \r\n");
      out.write("\t   \t\t<TD width=\"25%\"><font size = 2><center><img src=\"/LSJ_PHOTO/productImage/");
      out.print(p_image);
      out.write("\" height=\"50\"/></center></font></TD>      \r\n");
      out.write("\t  \t\t<TD width=\"40%\"><font size = 2><center>");
      out.print(p_name);
      out.write("</center></font></TD>      \r\n");
      out.write("\t  \t\t<TD width=\"20%\"><font size = 2><center>");
      out.print(p_price);
      out.write("원</center></font></TD>      \r\n");
      out.write("\t\t\t</TR> \r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t");

		} 
	}
	
      out.write("\r\n");
      out.write("\t<TR bgcolor = \"EAEAEA\">\r\n");
      out.write("\t<TD  ALIGN = \"left\" COLSPAN = \"4\"><font size = 2>총 가격 : ");
      out.print(allPrice);
      out.write("</font>\r\n");
      out.write("\t<INPUT TYPE = \"hidden\" NAME = \"price\" VALUE=\"");
      out.print(allPrice);
      out.write("\"></TD>\r\n");
      out.write("\t</TR>\t\r\n");
      out.write("\t</Table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<TABLE WIDTH = \"550\" BORDER = \"0\" CellPadding = \"5\" CellSpacing = \"0\">\r\n");
      out.write("\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD  ALIGN = \"left\" width=\"30%\"><font size = 2>주문자명</font></TD>\r\n");
      out.write("\t\t<TD  ALIGN = \"left\" width=\"70%\"><font size = 2> ");
      out.print(name );
      out.write("</font>\r\n");
      out.write("\t\t\t<INPUT TYPE = \"hidden\" SIZE = \"15\" MAXLENGTH = \"10\" NAME = \"name\" value=");
      out.print(name );
      out.write(">\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD  ALIGN = \"left\" width=\"30%\"><font size = 2>연락처</font></TD>\r\n");
      out.write("\t\t<TD  ALIGN = \"left\" width=\"70%\"><font size = 2> ");
      out.print(phone );
      out.write(" </font>\r\n");
      out.write("\t\t\t<INPUT TYPE = \"hidden\" SIZE = \"15\" MAXLENGTH = \"10\" NAME = \"name\" value=");
      out.print(phone );
      out.write(">\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD ALIGN = \"left\" width=\"30%\"><font size = 2>주소</font></TD>\r\n");
      out.write("\t\t<TD ALIGN = \"left\" width=\"70%\"><font size = 2> ");
      out.print(addr1 );
      out.write(" </font>\r\n");
      out.write("\t\t\t<INPUT TYPE =\"hidden\" NAME=\"addr1\" SIZE = \"50\" MAXLENGTH = \"50\" value=");
      out.print(addr1 );
      out.write(">\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD  ALIGN = \"left\" width=\"30%\"><font size = 2>상세주소</font></TD>\r\n");
      out.write("\t\t<TD  ALIGN = \"left\" width=\"70%\"><font size = 2> ");
      out.print(addr2 );
      out.write(" </font>\r\n");
      out.write("\t\t\t<INPUT TYPE =\"hidden\" NAME=\"addr2\" SIZE = \"50\" MAXLENGTH = \"50\" value=");
      out.print(addr2 );
      out.write(">\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD ALIGN = \"left\" width=\"30%\"><font size = 2>요청사항</font></TD>\r\n");
      out.write("\t\t<TD ALIGN = \"left\" width=\"70%\">\r\n");
      out.write("\t\t\t<TEXTAREA NAME=\"text\" ROWS=5 COLS=50></TEXTAREA>\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD  ALIGN = \"left\" width=\"30%\"><font size = 2>사진파일</font></TD>\r\n");
      out.write("\t\t<TD  ALIGN = \"left\" width=\"70%\">\r\n");
      out.write("\t\t\t<INPUT TYPE =\"file\" NAME=\"file\" >\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("\t<TR>\r\n");
      out.write("\t\t<TD ALIGN = \"center\" COLSPAN = \"2\"  width=\"100%\" height=\"40\">\r\n");
      out.write("\t\t<TABLE>\r\n");
      out.write("\t\t\t<TR>\r\n");
      out.write("\t\t\t\t<TD WIDTH = \"50%\" ALIGN = \"center\">\r\n");
      out.write("\t\t\t\t\t<INPUT TYPE = \"button\" VALUE = \"주문\" onClick=\"valid_check()\">\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t\t<TD WIDTH = \"50%\" ALIGN = \"center\">\r\n");
      out.write("\t\t\t\t\t<INPUT TYPE = \"button\" VALUE = \"취소\" onClick = \"submit_list()\">\r\n");
      out.write("\t\t\t\t</TD>\r\n");
      out.write("\t\t\t</TR>\r\n");
      out.write("\t\t</TABLE>\r\n");
      out.write("\t\t</TD>\r\n");
      out.write("\t</TR>\r\n");
      out.write("</TABLE>\r\n");

	}
	
	if(pstmt != null) pstmt.close();
	if(rs != null) rs.close();
	if(rs2 != null) rs2.close();
	if(rso != null) rso.close();
	if(con != null) con.close();

      out.write("\r\n");
      out.write("</FORM>\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
